### ISSUE TITLE
green read-length distribution plot for each barcoded sample

### ISSUE THREAD

**Issue by wososa** [tleonardi/pycoQC#125]
Hi @a-slide ,

Thanks for developing pycoQC. It is very useful! I hope to know if you can add a function for generating the green read-length distribution plot for each barcoded sample.

**Describe the solution you'd like**
Read-length distribution plot for each barcoded sample.

Thanks,
Woody

**Comment by a-slide** [comment]
Hi @wososa,
There are currently no plans to develop pycoQC further, other than maintaining it.
You can split your sequencing summary file by barcode with the barcode_split command and run pycoQC on the split files.
