### ISSUE TITLE
Interval Unit in Output over time plot

### ISSUE THREAD

**Issue by liscruk** [tleonardi/pycoQC#128]
Hi,

Thanks for maintaining and developing pycoQC. Great tool!

A brief question: 
Could you explain what the y-axis count unit is in the context of the interval line when looking at the output over time plot ?
I assumed that I was in billion bases (when looking at bases) however this does not fit really well to the total output.

The labels are just count and B so it is a little unclear what this actually denotes (or in what unit / scaling / factor ) they are measured.

Thanks !

**Comment by a-slide** [comment]
Hi @liscruk , 
By default the interval line is divided into 500 bins corresponding to total_time // 500
Then it is scaled to match the maximal height of the cumulative distribution.
So the number of the interval line don't really mean anything but it does for the cumulative distribution. It is there to give you an idea of what happened during the run.

Hope this helps

**Comment by liscruk** [comment]
Thanks, very helpful!
