### ISSUE TITLE
Repo URL is dead

### ISSUE THREAD

**Issue by ewels** [tleonardi/pycoQC#132]
Just wanted to point out that the URL on the GitHub repo now returns a 404: https://a-slide.github.io/pycoQC/

<img src="https://user-images.githubusercontent.com/465550/140888448-48404415-0ecb-4c94-9b6f-fa73c5169dc8.png" width=400>

**Comment by ewels** [comment]
Poking a bit more, I realise that it's because the URL redirects to https://adrienleger.com/pycoQC/ which is the one that's dead. Reports also follow the github.io link to this URL with the links in the header.

Ironically, the [_old_ repo](https://github.com/a-slide/pycoQC) does point to the new URL 😅 https://tleonardi.github.io/pycoQC/

**Comment by tleonardi** [comment]
Thanks for the report, fixed!
